(() => {
  const shell = document.querySelector('.game-shell');
  if (!shell || document.getElementById('matchGameStage')) return;

  const LOGO_BASE = 'assets/clubs/guatemala/';
  const ROLES = [['goalkeeper','Portero'],['defender','Defensa'],['midfielder','Mediocampista'],['forward','Delantero']];
  const style = document.createElement('link'); style.rel = 'stylesheet'; style.href = 'css/match-game.css?v=3.1.2'; document.head.appendChild(style);

  const stage = document.createElement('section'); stage.id = 'matchGameStage'; stage.className = 'screen secondary-screen match-game-scene';
  stage.innerHTML = `<div class="match-game-shell">
    <header class="match-game-header"><button id="matchGameBack" class="match-game-back" type="button">← Volver al club</button><div class="match-scoreboard"><div><strong id="matchHomeCode">LOC</strong><span id="matchHomeScore">0</span></div><b id="matchClock">00'</b><div><span id="matchAwayScore">0</span><strong id="matchAwayCode">VIS</strong></div></div><button id="matchPauseButton" class="match-pause" type="button">⏸ Pausa</button></header>
    <main class="turn-match-main"><section class="turn-field-wrap"><div class="turn-field"><div class="turn-goal turn-goal-home"></div><div class="turn-goal turn-goal-away"></div><div class="turn-half-line"></div><div class="turn-center-circle"></div><div id="homePieces" class="turn-team turn-team-home"></div><div id="awayPieces" class="turn-team turn-team-away"></div></div><div id="matchEvent" class="match-event">El partido está listo.</div></section><aside class="turn-panel"><p class="eyebrow">TU TURNO</p><h2 id="turnTitle">Preparando partido</h2><p id="turnDescription">Cada ronda permite una sola acción antes de que responda el rival.</p><div id="turnActions" class="turn-actions"></div><div class="turn-rule"><strong>1 acción</strong><span>por turno</span></div><button id="matchStartButton" class="match-start" type="button">Comenzar partido</button></aside></main>
    <footer class="turn-footer"><span>Portero → Defensa → Mediocampista → Delantero</span><strong id="possessionLabel">Posesión: —</strong><span>El delantero es el único que puede disparar.</span></footer>
    <div id="goalCelebration" class="goal-celebration" hidden><div class="goal-celebration-card"><div class="goal-word">¡GOOOOOOL!</div><img id="goalClubLogo" alt="Escudo del club"><strong id="goalPlayerName">Jugador</strong><span id="goalClubName">Club</span><b id="goalScoreText">1 - 0</b></div></div>
    <div id="pauseOverlay" class="match-pause-overlay" hidden><div class="match-pause-card"><p class="eyebrow">PARTIDO EN PAUSA</p><h2>La historia espera.</h2><p>El turno actual queda detenido hasta que decidas continuar.</p><button id="resumeMatchButton" type="button">Continuar</button><button id="pauseRulesButton" type="button">Reglas del partido</button><button id="abandonMatchButton" class="is-danger" type="button">Abandonar partido</button><div id="pauseRules" class="pause-rules" hidden>Una acción por turno. Portero ataja y distribuye; Defensa recupera y pasa; Mediocampista crea; Delantero dispara. Los pases pueden ser interceptados y los tiros pueden terminar fuera, atajados o en gol.</div></div></div>
  </div>`; shell.appendChild(stage);

  const homePieces=document.getElementById('homePieces'),awayPieces=document.getElementById('awayPieces'),homeScoreEl=document.getElementById('matchHomeScore'),awayScoreEl=document.getElementById('matchAwayScore'),homeCodeEl=document.getElementById('matchHomeCode'),awayCodeEl=document.getElementById('matchAwayCode'),clockEl=document.getElementById('matchClock'),eventEl=document.getElementById('matchEvent'),turnTitle=document.getElementById('turnTitle'),turnDescription=document.getElementById('turnDescription'),turnActions=document.getElementById('turnActions'),possessionLabel=document.getElementById('possessionLabel'),startButton=document.getElementById('matchStartButton'),pauseButton=document.getElementById('matchPauseButton'),pauseOverlay=document.getElementById('pauseOverlay'),goalCelebration=document.getElementById('goalCelebration');

  let homeClub=null,awayClub=null,homeLineup=null,awayLineup=null,possession={side:'home',role:'goalkeeper'},minute=0,homeScore=0,awayScore=0,running=false,paused=false,resolving=false,halftimeShown=false,shotBonus={home:0,away:0},pendingAssist={home:null,away:null},matchStats={},goalLog=[];

  function loadState(){try{const histories=JSON.parse(localStorage.getItem('lhdf.histories')||'[]');const id=localStorage.getItem('lhdf.currentHistoryId');return{histories,history:histories.find((item)=>item.id===id)||null};}catch(error){return{histories:[],history:null};}}
  const clubInfo=(id)=>window.LHDF_DATA?.clubs?.find((club)=>club.id===id)||null,playerInfo=(id)=>window.LHDF_DATA?.players?.find((player)=>player.id===id)||null,logoPath=(file)=>`${LOGO_BASE}${encodeURIComponent(file).replace(/%2F/g,'/')}`,codeFor=(club)=>(club?.name||'CLB').replace(/[^A-Za-zÁÉÍÓÚÜÑáéíóúüñ]/g,'').slice(0,3).toUpperCase(),chance=(p)=>Math.random()<p,pick=(min,max)=>Math.floor(Math.random()*(max-min+1))+min;
  function lineupFromState(state){if(!state?.lineup)return null;const lineup={};for(const[key]of ROLES){const player=playerInfo(state.lineup[key]);if(!player)return null;lineup[key]=player;}return lineup;}
  function stat(id,key,amount=1){matchStats[id]=matchStats[id]||{};matchStats[id][key]=(matchStats[id][key]||0)+amount;}
  const roleLabel=(role)=>ROLES.find(([key])=>key===role)?.[1]||role;
  function pieceMarkup(player,role,side){const owns=possession.side===side&&possession.role===role;return `<article class="turn-piece ${owns?'has-ball':''}" data-role="${role}"><span class="turn-role">${roleLabel(role)}</span><strong>${player.name}</strong><small>${player.position}</small>${owns?'<div class="turn-ball">⚽</div>':''}</article>`;}
  function renderField(){homePieces.innerHTML=ROLES.map(([key])=>pieceMarkup(homeLineup[key],key,'home')).join('');awayPieces.innerHTML=[...ROLES].reverse().map(([key])=>pieceMarkup(awayLineup[key],key,'away')).join('');const club=possession.side==='home'?homeClub:awayClub,lineup=possession.side==='home'?homeLineup:awayLineup;possessionLabel.textContent=`Posesión: ${club.name} · ${lineup[possession.role].name}`;homeScoreEl.textContent=String(homeScore);awayScoreEl.textContent=String(awayScore);clockEl.textContent=`${String(Math.min(minute,90)).padStart(2,'0')}'`;}
  function transitionTo(target){if(typeof fade!=='undefined')fade.classList.add('is-visible');window.setTimeout(()=>{document.querySelectorAll('.screen.active').forEach((screen)=>screen.classList.remove('active'));target.classList.add('active');if(typeof fade!=='undefined')requestAnimationFrame(()=>fade.classList.remove('is-visible'));},typeof TRANSITION_TIME==='number'?TRANSITION_TIME:480);}
  function prepareMatch(){window.ensureLHDFClubBeginning?.();const{history}=loadState(),homeState=history?.clubStates?.[history.selectedClub],awayState=history?.clubStates?.[history.rivalClub];if(!homeState||!awayState)return false;homeClub=clubInfo(history.selectedClub);awayClub=clubInfo(history.rivalClub);homeLineup=lineupFromState(homeState);awayLineup=lineupFromState(awayState);if(!homeClub||!awayClub||!homeLineup||!awayLineup)return false;possession={side:'home',role:'goalkeeper'};minute=0;homeScore=0;awayScore=0;running=false;paused=false;resolving=false;halftimeShown=false;shotBonus={home:0,away:0};pendingAssist={home:null,away:null};matchStats={};goalLog=[];homeCodeEl.textContent=codeFor(homeClub);awayCodeEl.textContent=codeFor(awayClub);eventEl.textContent=`${homeClub.name} y ${awayClub.name} están listos.`;startButton.hidden=false;startButton.textContent='Comenzar partido';turnTitle.textContent='Partido por turnos';turnDescription.textContent='Avanza el balón por las cuatro zonas. Después de cada acción responderá el rival.';turnActions.innerHTML='';pauseButton.disabled=true;renderField();return true;}
  function advanceClock(){minute+=pick(2,4);if(!halftimeShown&&minute>=45){halftimeShown=true;minute=45;eventEl.textContent='45’ · Descanso. Los clubes reorganizan sus líneas.';}minute=Math.min(minute,90);renderField();}
  function setEvent(text){eventEl.textContent=`${String(Math.min(minute,90)).padStart(2,'0')}’ · ${text}`;}
  function transfer(side,fromRole,toRole,probability,options={}){const lineup=side==='home'?homeLineup:awayLineup,passer=lineup[fromRole];if(chance(probability)){possession={side,role:toRole};stat(passer.id,'passesCompleted');if(options.keyPass){stat(passer.id,'keyPasses');shotBonus[side]=.12;}if(toRole==='forward')pendingAssist[side]=passer.id;setEvent(`${passer.name} completa ${options.label||'el pase'} hacia ${lineup[toRole].name}.`);return true;}const other=side==='home'?'away':'home',interceptRole=toRole==='forward'?'defender':toRole==='midfielder'?'midfielder':'defender',otherLineup=other==='home'?homeLineup:awayLineup;possession={side:other,role:interceptRole};stat(otherLineup[interceptRole].id,'interceptions');shotBonus[side]=0;pendingAssist[side]=null;setEvent(`${otherLineup[interceptRole].name} intercepta el envío de ${passer.name}.`);return false;}
  function defensiveAction(side,type){const opponent=side==='home'?'away':'home';if(possession.side!==opponent)return false;const defending=side==='home'?homeLineup:awayLineup,attacking=opponent==='home'?homeLineup:awayLineup,map={goalkeeper:['forward',.2],defender:['forward',.34],midfielder:['midfielder',.46],forward:['defender',.56]},[defRole,base]=map[possession.role]||['midfielder',.4],defender=defending[defRole],carrier=attacking[possession.role],probability=type==='press'?base:Math.max(.2,base-.1);if(chance(probability)){possession={side,role:defRole};stat(defender.id,'recoveries');if(type==='press')stat(defender.id,'interceptions');pendingAssist[opponent]=null;shotBonus[opponent]=0;setEvent(`${defender.name} recupera el balón ante ${carrier.name}.`);return true;}setEvent(`${carrier.name} protege la posesión ante ${defender.name}.`);return false;}
  function shoot(side,style){const lineup=side==='home'?homeLineup:awayLineup,opponent=side==='home'?awayLineup:homeLineup,striker=lineup.forward,goalkeeper=opponent.goalkeeper;stat(striker.id,'shots');const onTarget=style==='placed'?.72:.59;if(!chance(onTarget)){possession={side:side==='home'?'away':'home',role:'goalkeeper'};shotBonus[side]=0;pendingAssist[side]=null;setEvent(`${striker.name} dispara, pero el balón se marcha fuera.`);return;}stat(striker.id,'shotsOnTarget');const saveProbability=Math.max(.2,(style==='placed'?.48:.4)-shotBonus[side]);if(chance(saveProbability)){stat(goalkeeper.id,'saves');possession={side:side==='home'?'away':'home',role:'goalkeeper'};shotBonus[side]=0;pendingAssist[side]=null;setEvent(`${goalkeeper.name} ataja el disparo de ${striker.name}.`);return;}if(side==='home')homeScore+=1;else awayScore+=1;stat(striker.id,'goals');stat(goalkeeper.id,'goalsConceded');if(pendingAssist[side]&&pendingAssist[side]!==striker.id)stat(pendingAssist[side],'assists');goalLog.push({side,scorerId:striker.id,assisterId:pendingAssist[side],minute:Math.min(minute,90)});shotBonus[side]=0;pendingAssist[side]=null;renderField();showGoal(side,striker);}
  function showGoal(side,striker){resolving=true;const club=side==='home'?homeClub:awayClub;document.getElementById('goalClubLogo').src=logoPath(club.logo);document.getElementById('goalPlayerName').textContent=striker.name;document.getElementById('goalClubName').textContent=club.name;document.getElementById('goalScoreText').textContent=`${homeScore} - ${awayScore}`;goalCelebration.hidden=false;window.setTimeout(()=>{goalCelebration.hidden=true;possession={side:side==='home'?'away':'home',role:'goalkeeper'};setEvent(`¡Gol de ${striker.name} para ${club.name}!`);renderField();resolving=false;if(minute>=90){finishMatch();return;}if(side==='home')afterHomeAction();else homeActions();},1900);}
  function homeActions(){if(!running||paused||resolving)return;turnActions.innerHTML='';turnTitle.textContent=possession.side==='home'?`${homeLineup[possession.role].name} tiene el balón`:`${awayClub.name} tiene la posesión`;turnDescription.textContent=possession.side==='home'?`Zona: ${roleLabel(possession.role)}. Elige una acción.`:'Puedes intentar recuperar el balón o replegarte antes del movimiento rival.';const actions=[];if(possession.side==='home'){if(possession.role==='goalkeeper')actions.push(['Pasar al defensa',()=>transfer('home','goalkeeper','defender',.94)]);if(possession.role==='defender'){actions.push(['Pase seguro al medio',()=>transfer('home','defender','midfielder',.84)],['Pase largo al delantero',()=>transfer('home','defender','forward',.52,{label:'un pase largo'})]);}if(possession.role==='midfielder'){actions.push(['Pase al delantero',()=>transfer('home','midfielder','forward',.78)],['Pase filtrado',()=>transfer('home','midfielder','forward',.6,{label:'un pase filtrado',keyPass:true})],['Devolver al defensa',()=>transfer('home','midfielder','defender',.9)]);}if(possession.role==='forward'){actions.push(['Tiro colocado',()=>shoot('home','placed')],['Tiro potente',()=>shoot('home','power')],['Devolver al medio',()=>transfer('home','forward','midfielder',.86)]);}}else{actions.push(['Presionar / robar',()=>defensiveAction('home','press')],['Replegar y cerrar espacios',()=>defensiveAction('home','drop')]);}actions.forEach(([label,fn])=>{const button=document.createElement('button');button.type='button';button.textContent=label;button.addEventListener('click',()=>executeHomeAction(fn),{once:true});turnActions.appendChild(button);});}
  function executeHomeAction(action){if(!running||paused||resolving)return;resolving=true;turnActions.querySelectorAll('button').forEach((button)=>button.disabled=true);action();advanceClock();if(!goalCelebration.hidden)return;afterHomeAction();}
  function afterHomeAction(){if(!running)return;if(minute>=90){finishMatch();return;}window.setTimeout(aiTurn,650);}
  function aiTurn(){if(!running||paused){resolving=false;return;}if(possession.side==='away'){const role=possession.role;if(role==='goalkeeper')transfer('away','goalkeeper','defender',.92);else if(role==='defender')chance(.28)?transfer('away','defender','forward',.5,{label:'un pase largo'}):transfer('away','defender','midfielder',.82);else if(role==='midfielder')chance(.35)?transfer('away','midfielder','forward',.58,{label:'un pase filtrado',keyPass:true}):transfer('away','midfielder','forward',.76);else if(role==='forward')shoot('away',chance(.5)?'placed':'power');}else defensiveAction('away',chance(.7)?'press':'drop');advanceClock();if(!goalCelebration.hidden)return;if(minute>=90){finishMatch();return;}resolving=false;homeActions();}
  function saveFirstResult(){const{histories,history}=loadState();if(!history||history.inauguralMatchCompleted)return;const homeState=history.clubStates?.[history.selectedClub],awayState=history.clubStates?.[history.rivalClub];if(!homeState||!awayState)return;[homeState,awayState].forEach((state)=>state.statistics.matches+=1);homeState.statistics.goalsFor+=homeScore;homeState.statistics.goalsAgainst+=awayScore;awayState.statistics.goalsFor+=awayScore;awayState.statistics.goalsAgainst+=homeScore;if(homeScore>awayScore){homeState.statistics.wins+=1;awayState.statistics.losses+=1;}else if(awayScore>homeScore){awayState.statistics.wins+=1;homeState.statistics.losses+=1;}else{homeState.statistics.draws+=1;awayState.statistics.draws+=1;}const allIds=[...Object.values(homeState.lineup||{}),...Object.values(awayState.lineup||{})];allIds.forEach((id)=>{history.playerStates[id]=history.playerStates[id]||{stats:{},history:[]};history.playerStates[id].stats=history.playerStates[id].stats||{};history.playerStates[id].stats.matches=(history.playerStates[id].stats.matches||0)+1;Object.entries(matchStats[id]||{}).forEach(([key,value])=>history.playerStates[id].stats[key]=(history.playerStates[id].stats[key]||0)+value);});const homeGK=homeState.lineup?.goalkeeper,awayGK=awayState.lineup?.goalkeeper;if(awayScore===0&&homeGK)history.playerStates[homeGK].stats.cleanSheets=(history.playerStates[homeGK].stats.cleanSheets||0)+1;if(homeScore===0&&awayGK)history.playerStates[awayGK].stats.cleanSheets=(history.playerStates[awayGK].stats.cleanSheets||0)+1;goalLog.forEach((goal)=>{const scorer=playerInfo(goal.scorerId),state=history.playerStates[goal.scorerId];state.history=Array.isArray(state.history)?state.history:[];state.history.push({type:'goal',date:`${goal.minute}'`,title:'Gol',description:`${scorer.name} marcó en el partido inaugural de esta historia.`});});const resultText=`${homeClub.name} ${homeScore} - ${awayScore} ${awayClub.name}`;homeState.history=homeState.history||[];homeState.history.push({type:'match',date:'Partido inaugural',title:'Primer partido disputado',description:resultText});history.matches=Array.isArray(history.matches)?history.matches:[];history.matches.push({type:'inaugural',homeClubId:homeClub.id,awayClubId:awayClub.id,homeScore,awayScore,goals:goalLog,playedAt:new Date().toISOString()});history.inauguralMatchCompleted=true;history.updatedAt=new Date().toISOString();localStorage.setItem('lhdf.histories',JSON.stringify(histories));if(typeof renderSavedHistories==='function')renderSavedHistories();}
  function finishMatch(){if(!running)return;running=false;resolving=false;pauseButton.disabled=true;turnActions.innerHTML='';minute=90;renderField();saveFirstResult();const result=homeScore===awayScore?'Empate':homeScore>awayScore?`Victoria de ${homeClub.name}`:`Victoria de ${awayClub.name}`;turnTitle.textContent='Final del partido';turnDescription.textContent=`${result}. Marcador final: ${homeScore} - ${awayScore}.`;eventEl.textContent=`90’ · Final: ${homeClub.name} ${homeScore} - ${awayScore} ${awayClub.name}`;startButton.hidden=false;startButton.textContent='Repetir prueba';}
  function startMatch(){if(!prepareMatch())return;running=true;pauseButton.disabled=false;startButton.hidden=true;setEvent(`Comienza el partido. ${homeLineup.goalkeeper.name} tiene la primera posesión.`);renderField();homeActions();}
  window.showInauguralMatch=function(){if(!prepareMatch()){window.alert('Primero entra a tu club para preparar la plantilla inicial.');return;}transitionTo(stage);};
  function installLauncher(){const options=document.querySelector('.club-menu-options');if(!options)return;document.getElementById('clubPlayMatchButton')?.remove();const button=document.createElement('button');button.id='clubPlayMatchButton';button.className='club-menu-option club-match-launch is-active';button.type='button';button.innerHTML='<em>Jugable · prueba 3</em><strong>Partido inaugural</strong><span>Partido táctico por turnos con Portero, Defensa, Mediocampista y Delantero.</span>';button.addEventListener('click',(event)=>{event.stopPropagation();window.showInauguralMatch();});options.appendChild(button);}
  startButton.addEventListener('click',startMatch);document.getElementById('matchGameBack').addEventListener('click',()=>{running=false;paused=false;window.showOwnedClubMenu?.();});pauseButton.addEventListener('click',()=>{if(!running||resolving)return;paused=true;pauseOverlay.hidden=false;});document.getElementById('resumeMatchButton').addEventListener('click',()=>{paused=false;pauseOverlay.hidden=true;homeActions();});document.getElementById('pauseRulesButton').addEventListener('click',()=>{const rules=document.getElementById('pauseRules');rules.hidden=!rules.hidden;});document.getElementById('abandonMatchButton').addEventListener('click',()=>{if(!window.confirm('¿Abandonar este partido? El resultado no se guardará.'))return;running=false;paused=false;pauseOverlay.hidden=true;window.showOwnedClubMenu?.();});installLauncher();window.setTimeout(installLauncher,900);
})();